# Generated by Django 4.2.13 on 2024-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('google', 'Google')], default='email', max_length=10),
        ),
    ]
